Repository skillprompt/skill-ecom, pull requests merged in 2024-05, with the labels that each got.

#33 added the contact us form
  public/newTestLogo.png
  public/textLogo.png
  src/App.tsx
  src/components/CategoryCard.tsx
  src/components/ContractUsForm.tsx
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/components/ProductCards.tsx
  src/data/Categories.tsx
  src/data/Products.tsx
  src/types/categoriesType.ts
  src/types/productsType.ts
  tailwind.config.js
Labels: frontend

#34 made enhancement on ui & ux
  src/App.tsx
  src/components/CategoryCard.tsx
  src/components/ForgotPasswordModal.tsx
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/components/ProductCards.tsx
  src/data/Categories.tsx
  src/data/Products.tsx
  src/types/categoriesType.ts
  src/types/productsType.ts
Labels: enhancement

#35 Footer banner
  public/Bbanner.png
  public/Image.png
  public/Instagram.png
  public/Mac1 .png
  public/Vector.png
  public/guarante.png
  public/pImage.png
  public/phoneimg.png
  public/tiktok.png
  src/App.tsx
  src/components/Banner.tsx
  src/components/Card.tsx
  src/components/Detail.tsx
  src/components/Footer.tsx
  src/components/breadcrumbs.tsx
  src/components/sidebar.tsx
  src/main.tsx
  vite.config.ts.timestamp-1714887135641-5364872487bad.mjs
Labels: design, frontend

#36 Navbar
  app/globals.css
  components.json
  index.html
  package-lock.json
  package.json
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/components/NavbarModal.tsx
  src/components/ProductCards.tsx
  src/components/ui/dropdown-menu.tsx
  src/lib/utils.ts
  src/store/loginStore.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: frontend

#40 added the checkout page with dummy data
  src/App.tsx
  src/components/CheckoutCart.tsx
  src/components/CheckoutPage.tsx
  src/components/CheckoutTab.tsx
  src/components/HomePageContainer.tsx
  src/components/Navbar.tsx
  src/icons/Cross.tsx
  src/icons/Minus.tsx
  src/icons/Plus.tsx
  src/types/tempShoppingCart.ts
  tailwind.config.js
  yarn.lock
Labels: frontend

#45 Discount card
  public/discount1.png
  public/discount4.png
  src/components/CategoryCard.tsx
  src/components/DiscountCard.tsx
  src/components/HomePageContainer.tsx
  src/data/DiscountProducts.ts
Labels: frontend

#49 redesigned the ui for admin side
  src/App.tsx
  src/components/Adminpanel/AdminNavbar.tsx
  src/components/Adminpanel/Categories.tsx
  src/components/Adminpanel/Products.tsx
  src/components/Adminpanel/Sidebar.tsx
  src/components/Adminpanel/Users.tsx
  src/components/SearchPage.tsx
Labels: frontend

#50 added login and forgot-password modal
  src/components/Banner3.png
  src/components/HomePageForgotPasswordModal.tsx
  src/components/LoginModal.tsx
  src/components/Navbar.tsx
  src/store/forgotPasswordModalStore.ts
  src/store/loginModalStore.ts
  yarn.lock
Labels: enhancement, frontend

#51 Zod validation
  package.json
  src/App.tsx
  src/components/CheckoutCart.tsx
  src/components/ContractUsForm.tsx
  src/components/FlowbiteReact/HomePageForgotPasswordModal.tsx
  src/components/FlowbiteReact/LoginModal.tsx
  src/components/FlowbiteReact/RemoveWishlistModal.tsx
  src/components/FlowbiteReact/SearchFilterDropdown.tsx
  src/components/FlowbiteReact/SearchPagination.tsx
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/components/Register.tsx
  src/components/SearchPage.tsx
  src/components/Wishlist.tsx
  src/components/order.tsx
  src/data/productItems.ts
  src/data/search.ts
  src/icons/category-card-icons/DarkCamera.tsx
  src/icons/category-card-icons/DarkComputer.tsx
  src/icons/category-card-icons/DarkGaming.tsx
  src/icons/category-card-icons/DarkHeadPhones.tsx
  src/icons/category-card-icons/DarkPhone.tsx
  src/icons/category-card-icons/DarkSmartWatch.tsx
  src/icons/footer/Instagram.tsx
  src/icons/home.tsx
  src/icons/mobile.tsx
  src/icons/navbar/Search.tsx
  src/store/wishlistStore.ts
  src/validation/registervalidation.ts
  yarn.lock
Labels: design, enhancement

#52 added hookform-resolver in login page
  src/App.tsx
  src/components/HomePageContainer.tsx
  src/components/Navbar.tsx
  src/pages/Checkout.tsx
  src/pages/ContactUs.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/Search.tsx
  src/pages/Wishlist.tsx
  src/store/loginStore.ts
  src/types/type.ts
Labels: enhancement

#53 designed the category page
  src/App.tsx
  src/components/Adminpanel/Category.tsx
  src/components/Adminpanel/Sidebar.tsx
  src/data/CategoryData.tsx
Labels: design
