Repository skillprompt/skill-ecom, pull requests merged in 2024-04, with the labels that each got.

#10 Login
  package-lock.json
  package.json
  postcss.config.js
  public/HaatBazaarLogo.svg
  public/angry.jpg
  src/App.css
  src/App.tsx
  src/components/LoginPage.tsx
  src/index.css
  src/type.tsx
  tailwind.config.js
Labels: frontend

#11 Register
  flowbite-react-app/.eslintrc.cjs
  flowbite-react-app/.gitignore
  flowbite-react-app/.vscode/extensions.json
  flowbite-react-app/LICENSE
  flowbite-react-app/README.md
  flowbite-react-app/index.html
  flowbite-react-app/package-lock.json
  flowbite-react-app/package.json
  flowbite-react-app/postcss.config.js
  flowbite-react-app/prettier.config.js
  flowbite-react-app/public/vite.svg
  flowbite-react-app/src/App.tsx
  flowbite-react-app/src/index.css
  flowbite-react-app/src/main.tsx
  flowbite-react-app/src/vite-env.d.ts
  flowbite-react-app/tailwind.config.js
  flowbite-react-app/tsconfig.json
  flowbite-react-app/tsconfig.node.json
  flowbite-react-app/vite.config.ts
  package-lock.json
  package.json
  public/logo.jpg.png
  public/logo.svg
  src/App.tsx
  src/components/LoginPage.tsx
  src/components/Register.tsx
  src/data/registerTypes.ts
  src/store/store.ts
  tailwind.config.js
Labels: frontend

#15 Login
  index.html
  src/components/LoginPage.tsx
  src/data/type.tsx
  tailwind.config.js
Labels: frontend

#16 fixed the length of input for security
  src/components/LoginPage.tsx
Labels: frontend, security

#13 Created the Navbar
  package-lock.json
  src/App.tsx
  src/Component/Nabbar.tsx
  src/images/cart.png
  src/images/logo.svg
  src/index.css
Labels: frontend

#17 made changes in the navbar component
  public/logo2.png
  src/App.tsx
  src/Component/Nabbar.tsx
  src/components/Navbar.tsx
Labels: frontend

#18 Register
  package-lock.json
  package.json
  public/angry.jpg
  public/logo.jpg.png
  src/App.tsx
  src/assets/react.svg
  src/components/Register.tsx
  src/data/registerTypes.ts
  src/validation/registervalidation.ts
  tailwind.config.js
Labels: frontend

#21 adding notification
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoginPage.tsx
  src/components/Register.tsx
  src/data/AsignRole.ts
  src/types/registerTypes.ts
  src/types/type.ts
  src/validation/registervalidation.ts
Labels: frontend

#23 added the feature for forgot password
  package-lock.json
  package.json
  src/components/ForgotPasswordModal.tsx
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/images/logo.svg
  src/index.css
  src/store/loginStore.ts
  src/store/store.ts
  src/types/type.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement, frontend

#25 added the feature for reseting the password
  src/App.tsx
  src/components/ForgotPasswordModal.tsx
  src/components/LoginPage.tsx
  src/components/NewPasswordForm.tsx
  src/store/loginStore.ts
  src/types/type.ts
Labels: enhancement, frontend

#26 enhanced the feature
  src/components/ForgotPasswordModal.tsx
  src/components/LoginPage.tsx
  src/components/NewPasswordForm.tsx
  src/store/loginStore.ts
Labels: enhancement

#27 enhanced the enhancement
  src/components/ForgotPasswordModal.tsx
  src/components/LoginPage.tsx
  src/components/NewPasswordForm.tsx
Labels: enhancement

#29 made the login page responsive
  src/components/LoginPage.tsx
  src/components/Navbar.tsx
  src/images/cart.png
Labels: enhancement, frontend

#30 add the category bar and carousel
  package-lock.json
  package.json
  public/Banner1.png
  public/Banner2.png
  public/Banner3.png
  public/camera.png
  public/headphone.png
  public/mbl.png
  public/newLogo.png
  public/smartWatch.png
  src/App.tsx
  src/components/CarouselComponent.tsx
  src/components/CategoryBar.tsx
  src/components/Navbar.tsx
  tailwind.config.js
  yarn.lock
Labels: frontend

#31 Rajan dashboard
  package-lock.json
  package.json
  public/logo.png
  public/orders.png
  public/products.png
  src/App.tsx
  src/components/Adminpanel/AddProduct.tsx
  src/components/Adminpanel/AdminNavbar.tsx
  src/components/Adminpanel/AdminPanel.tsx
  src/components/Adminpanel/Categories.tsx
  src/components/Adminpanel/Dashboard.tsx
  src/components/Adminpanel/Orders.tsx
  src/components/Adminpanel/Products.tsx
  src/components/Adminpanel/Sidebar.tsx
  src/components/Adminpanel/Users.tsx
  tailwind.config.js
  yarn.lock
Labels: frontend

#32 Category card
  package-lock.json
  package.json
  public/airmax.png
  public/applewatch.png
  public/camera.png
  public/galaxyfoldphone.png
  public/ipad.png
  public/iphone14.png
  public/iphone2.png
  public/samsungwatch.png
  src/App.tsx
  src/components/CategoryCard.tsx
  src/components/ForgotPasswordModal.tsx
  src/components/HomePageContainer.tsx
  src/components/LoginPage.tsx
  src/components/NewPasswordForm.tsx
  src/components/ProductCards.tsx
  src/components/Register.tsx
  src/index.css
  yarn.lock
Labels: frontend
