Repository skillprompt/skill-ecom, pull requests merged in 2024-06, with the labels that each got.

#54 Fetch products category
  package.json
  src/App.tsx
  src/components/Adminpanel/AddProduct.tsx
  src/components/Adminpanel/Category.tsx
  src/components/Adminpanel/CreateCategoryModal.tsx
  src/components/Adminpanel/DeleteCategoryModal.tsx
  src/components/Adminpanel/EditCategoryModal.tsx
  src/data/CategoryData.tsx
  src/pages/Login.tsx
  src/store/admin/categoryStore.ts
  src/store/loginStore.ts
  src/types/TCreateProduct.ts
  src/types/admin/TCategory.ts
  src/validation/addProductValidation.ts
  tailwind.config.js
  yarn.lock
Labels: design

#55 fixed the problem for unauthorized request
  src/components/Adminpanel/AddProduct.tsx
  src/components/Adminpanel/Category.tsx
  src/components/Adminpanel/CreateCategoryModal.tsx
  src/components/Adminpanel/DeleteCategoryModal.tsx
  src/components/Adminpanel/EditCategoryModal.tsx
  src/components/Adminpanel/Sidebar.tsx
  src/pages/Login.tsx
Labels: bug

#56 first querry code
  src/components/Adminpanel/Products.tsx
  src/data/productData.tsx
  src/icons/wishlistData.ts
  src/store/wishlistStore.ts
Labels: frontend
